### ISSUE TITLE
[octodroid] java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by rikarumi** [rikarumi/Githubsampleapp#1]
hi @rejasupotaro, I am facing following error while running the project. Do you know what might trigger this to happen? 
cc: @hardwinder @firewalker06

```
03-12 15:13:04.585  16583-16583/com.githubsample.rika.githubsampleapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.githubsample.rika.githubsampleapp, PID: 16583
    java.lang.NoClassDefFoundError: com.rejasupotaro.octodroid.GitHubClient$1
            at com.rejasupotaro.octodroid.GitHubClient.user(GitHubClient.java:39)
            at com.githubsample.rika.githubsampleapp.MainActivity.loginGithub(MainActivity.java:89)
            at com.githubsample.rika.githubsampleapp.MainActivity$1.onClick(MainActivity.java:55)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19969)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```

**Comment by rejasupotaro** [comment]
Octodroid is using GSON (that is serialize/deserialize library) internally. So you need to include dependency.
I'm sorry for lack of information :bow: 

``` java
// app/build.gradle
dependencies {
    ...
    compile 'com.google.code.gson:gson:2.3.1'`
}
```

**Comment by rikarumi** [comment]
thanks @rejasupotaro :tada:  works perfectly now :+1:
